# This Docker Compose YAML deploys a MySQL database
services:
  worksocial-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sistine03
      MYSQL_DATABASE: worksocial-db
      MYSQL_USER: pilgrim
      MYSQL_PASSWORD: sistine03
    ports:
      - 3308:3306
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d