# This Docker Compose YAML deploys a MySQL database
services:
  worksocial-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: worksocial-db
      MYSQL_USER: pilgrim
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - 3308:3306
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

secrets:
  db_root_password:
    file: db_password.txt
  db_password:
    file: db_password.txt